---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	planner(planner)
	supervisor(supervisor)
	web_research(web_research)
	kb_research(kb_research)
	aggregator(aggregator)
	fact_check(fact_check)
	writer(writer)
	__end__([<p>__end__</p>]):::last
	__start__ --> planner;
	aggregator --> fact_check;
	fact_check -.-> supervisor;
	fact_check -.-> writer;
	kb_research --> aggregator;
	planner --> supervisor;
	supervisor --> kb_research;
	supervisor --> web_research;
	web_research --> aggregator;
	writer --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
